version: "3.9"

services:
  wmgtss:
    # Build Q&A Board service based on the Dockerfile in this repo
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations board &&
             python manage.py migrate &&
             python manage.py loaddata sample_db.json &&
             python manage.py runserver 0.0.0.0:8000"

    # Map port 8000 on the local machine to the port 8000 in the container
    ports:
      - "8000:8000"
    # Connect app folder in this repo to the app folder in the container
    # Allows for changes in the repo to be displayed without rebuild of docker image
    volumes:
      - ./app:/app
    # Sets environment vairables in the container for use by Django
    environment:
      - SECRET_KEY=developmentSecretKey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
      - ALLOWED_HOSTS=0.0.0.0,localhost
    # Docker will enable the db service before the Django app since there is a dependency 
    depends_on:
      - db

  db:
    # Build database from postgres image for alpine
    image: postgres:13.5-alpine3.15
    # Set environment variables for the database
    # Since this is the dev enviroment, exposing the user and password is not a security risk
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
